name: Deploy Backend to Server

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy-backend-server.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Create data directory
        run: mkdir -p data

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src/,package.json,package-lock.json,env.example,data/"
          target: ${{ secrets.SERVER_TARGET_PATH }}
          strip_components: 0

      - name: Install dependencies on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_TARGET_PATH }}
            npm ci --production
            cp env.example .env
            echo "Please update .env file with your API keys"

      - name: Restart service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_TARGET_PATH }}
            if pm2 list | grep -q "findlanqbot"; then
              pm2 restart findlanqbot
            else
              pm2 start src/app.js --name findlanqbot
            fi 